name: macos-10.15
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [macos-10.15]
        #python-version: [ 3.5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
            brew install cmake ccache conan python3 libiconv

      - name: install conan
        run: |
          conan user
          conan remote add cyberduckninja http://conan.cyberduckninja.com:9300

      - name: build
        run: |
          cmake . -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON
          cmake --build . --parallel 2

      - name: install dependons test
        run: pip install -r apps/rocketjoe_kernel/test/requirements.txt

      - name: install kernel
        run: jupyter kernelspec install --user kernels/rocketjoe

      - name: run test base
        run: pytest apps/rocketjoe_kernel/test/test_jupyter_kernel.py

      - name: run benchmark base
        run: |
          pytest apps/rocketjoe_kernel/test/test_jupyter_kernel_benchmark.py

      #- name: run test kernel_info
      #  run: pytest apps/rocketjoe_kernel/test/test_jupyter_kernel_raw.py