FROM debian:buster-backports

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        cmake \
        ninja-build \
        python3-pip \
        ipython3 \
        jupyter && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir conan ipyparallel

WORKDIR /app

COPY conanfile.txt ./

RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan && \
    conan remote add jinncrafters https://api.bintray.com/conan/jinncrafters/conan && \
    conan install . --build missing -s build_type=Debug -s compiler.libcxx=libstdc++11

COPY . ./

WORKDIR ./build

RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug && \
    cmake --build . && \
    jupyter kernelspec install --user kernels/ipython && \
    mkdir -p rocketjoe

WORKDIR rocketjoe

CMD (nohup ipcontroller &) && \
    while [ ! -f /root/.ipython/profile_default/security/ipcontroller-engine.json ]; do sleep 1; done \
    && echo -e "address: 127.0.0.1\n\
websocket-port: 9999\n\
http-port: 9998\n\
ipc_message_queue_id: 424cdc45-e1c0-4116-88b6-e14030bfc1c9" > config.yaml \
    && (nohup ../rocketjoed/rocketjoed --jupyter_mode --worker_mode \
           --jupyter_connection /root/.ipython/profile_default/security/ipcontroller-engine.json &) \
    && sleep 3 \
    && sed -i 's/9998/10998/g' config.yaml && sed -i 's/9999/10999/g' config.yaml \
    && (nohup ../rocketjoed/rocketjoed --jupyter_mode --worker_mode \
           --jupyter_connection /root/.ipython/profile_default/security/ipcontroller-engine.json &) \
    && sleep 3 \
    && sed -i 's/10998/11998/g' config.yaml && sed -i 's/10999/11999/g' config.yaml \
    && jupyter notebook --no-browser --allow-root \
        --NotebookApp.allow_remote_access=True --NotebookApp.ip=0.0.0.0

EXPOSE 8888
