PUT http://127.0.0.1:9998/cube
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{"jsonrpc":"2.0","method":"update","params":{"table":"lab","find":{"name":"mordo"}},"id":"0","application-id":"1qaz","api-key": "1qaz"}
###


