FROM centos:6.10

ENV AUDITWHEEL_ARCH x86_64
ENV AUDITWHEEL_PLAT manylinux2010_$AUDITWHEEL_ARCH
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV DEVTOOLSET_ROOTPATH /opt/rh/devtoolset-8/root
ENV PATH $DEVTOOLSET_ROOTPATH/usr/bin:$PATH
ENV LD_LIBRARY_PATH $DEVTOOLSET_ROOTPATH/usr/lib64:$DEVTOOLSET_ROOTPATH/usr/lib:$DEVTOOLSET_ROOTPATH/usr/lib64/dyninst:$DEVTOOLSET_ROOTPATH/usr/lib/dyninst:/usr/local/lib64:/usr/local/lib
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig

COPY ./centos6/build_scripts /build_scripts
RUN bash build_scripts/build.sh && rm -r build_scripts

ENV SSL_CERT_FILE=/opt/_internal/certs.pem

RUN /opt/python/cp37-cp37m/bin/pip install conan cmake

RUN ln -s /opt/python/cp37-cp37m/bin/conan /usr/bin/conan

RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
RUN conan remote add cyberduckninja https://api.bintray.com/conan/cyberduckninja/conan
RUN conan profile new default --detect
RUN conan profile update settings.compiler.libcxx=libstdc++11 default

RUN rm /usr/bin/python
RUN ln -s /opt/python/cp37-cp37m/bin/python /usr/bin/python

RUN ln -s /opt/python/cp37-cp37m/bin/cmake /usr/bin/cmake

WORKDIR /app


RUN conan install botan/2.13.0@cyberduckninja/stable -b missing -o:without_os_feature=getauxval
RUN conan install \
             -b missing \
             -b boost \
             -b fmt \
             -b spdlog \
             -b botan \
             -b libsodium \
             -s build_type=Debug \
             -s compiler.libcxx=libstdc++11 \
             conanfile.txt
