FROM ubuntu:20.04 as builder

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        software-properties-common ca-certificates \
        ninja-build make \
        python3-pip python3 python3-dev python3-setuptools \
        zlib1g-dev wget && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 16 && \
    apt install -y clang-16 lld-16 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-16 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-16 100 && \
    update-alternatives --config c++ && \
    update-alternatives --config cc && \
    clang++-16 --version


ENV CC clang-16
ENV CXX clang++-16

RUN pip3 install --no-cache-dir conan==1.64 pytest==6.2.5 cmake && \
    conan user && \
    update-alternatives --install /usr/bin/cc cc /usr/bin/clang-16 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-16 100 && \
    update-alternatives --config c++ && \
    update-alternatives --config cc && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan remote add duckstax http://conan.duckstax.com

WORKDIR /app/build
COPY conanfile.txt ./conanfile.txt
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang-16 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-16 100 && \
    conan install conanfile.txt --build missing -s build_type=Release

WORKDIR /app
COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./example ./example
COPY ./CMakeLists.txt ./CMakeLists.txt

WORKDIR /app/build

RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang-16 100 && \
    update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-16 100 && \
    cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON -DCMAKE_C_COMPILER=/usr/bin/clang-16 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-16  && \
    cmake --build . --target all -- -j $(nproc)

RUN ctest -C -V --output-on-failure --timeout 60

RUN cd integration/python/ && pytest

# Multistage build is faster and resulting image will be smaller
FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app
COPY --from=builder /app ./

RUN cd integration/csharp && \
    dotnet restore ./src/Duckstax.Otterbrix/Duckstax.Otterbrix.csproj && \
    dotnet restore ./tests/Duckstax.Otterbrix.Tests/Duckstax.Otterbrix.Tests.csproj

RUN mkdir -p integration/csharp/src/Duckstax.Otterbrix/bin/Release/net7.0 && \
    mkdir -p integration/csharp/tests/Duckstax.Otterbrix.Tests/bin/Release/net7.0 && \
    cp ./build/integration/c/libotterbrix.so ./integration/csharp/src/Duckstax.Otterbrix/bin/Release/net7.0/libotterbrix.so && \
    cp ./build/integration/c/libotterbrix.so ./integration/csharp/tests/Duckstax.Otterbrix.Tests/bin/Release/net7.0/libotterbrix.so

RUN cd integration/csharp && \
    dotnet test -c Release