FROM ubuntu:20.04

RUN ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        cmake \
        ninja-build \
        python3-pip \
        python3-venv \
        python3-dev curl gnupg apt-transport-https && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | apt-key add && \
        echo 'deb https://storage.googleapis.com/bazel-apt stable jdk1.8' | tee /etc/apt/sources.list.d/bazel.list && \
        apt update && \
        apt install -y bazel bazel-4.1.0 python3-pip git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir conan==1.48.0 pytest==6.2.5 && \
    conan user && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan remote add duckstax http://conan.duckstax.com:9300


WORKDIR /app/build

COPY conanfile.txt ./

RUN conan install . --build missing -s build_type=Release

COPY conan/profiles/wasm ./conan/profiles/wasm
RUN conan config install conan
COPY conanfile-wasm.txt ./
RUN conan install -pr wasm --profile:build=default --profile:host=wasm --build missing -s build_type=Release conanfile-wasm.txt -if=./wasm  -of=./wasm

COPY ./apps ../apps
COPY ./cmake ../cmake
COPY ./components ../components
COPY ./core ../core
COPY ./services ../services
COPY ./wasm ../wasm
COPY ./CMakeLists.txt ../CMakeLists.txt

WORKDIR /app/build
RUN conan install emsdk/3.1.16@_/_ -g virtualenv  -s build_type=Release --build missing
#RUN  ./activate.sh
#ENV VIRTUAL_ENV=/opt/venv
#RUN python3 -m venv  $VIRTUAL_ENV
#ENV PATH="$VIRTUAL_ENV/bin:$PATH"
#RUN which source
#RUN /bin/bash -c "source ./activate.sh " &&
ENV EMSDK="/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8"
ENV EMSCRIPTEN="/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8/bin/upstream/emscripten"
ENV EM_CONFIG="/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8/bin/.emscripten"
ENV EM_CACHE="/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8/bin/.emscripten_cache"
ENV PATH="/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8":"/root/.conan/data/emsdk/3.1.16/_/_/package/2880313eadc30db92089af7733fe8364772ee5c8/bin/upstream/emscripten":"/root/.conan/data/nodejs/16.3.0/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin"${PATH:+:$PATH}


RUN cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake -DDEV_MODE=OFF -DWASM_BUILD=ON
RUN cmake --build .

RUN cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=OFF -DWASM_BUILD=ON
RUN cmake --build .

CMD ctest -V
CMD pytest
