FROM debian:buster-backports

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        cmake \
        ninja-build \
        python3-pip &&\
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir conan ipyparallel

WORKDIR /app

COPY ./conanfile.txt ./

RUN ln -s /usr/bin/python3 /usr/bin/python

RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan && \
    conan remote add cyberduckninja https://api.bintray.com/conan/cyberduckninja/conan && \
    conan install . --build missing -s build_type=Release -s compiler.libcxx=libstdc++11

COPY . ./

WORKDIR ./build

RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON  && \
    cmake --build .                                            && \
    jupyter kernelspec install --user kernels/ipython          && \
    mkdir -p rocketjoe

WORKDIR rocketjoe

CMD (nohup ipcontroller --debug &) && \
    while [ ! -f /root/.ipython/profile_default/security/ipcontroller-engine.json ]; do sleep 1; done \
    && (nohup ../rocketjoed/rocketjoed --jupyter_engine --worker_mode \
         --jupyter_connection /root/.ipython/profile_default/security/ipcontroller-engine.json &) \
    && (nohup ../rocketjoed/rocketjoed --jupyter_engine --worker_mode \
         --jupyter_connection /root/.ipython/profile_default/security/ipcontroller-engine.json &) \
    && sleep 10 \
    && ../rocketjoed/rocketjoed ../rocketjoed/test/script_mode.py