FROM ubuntu:bionic

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        cmake \
        ninja-build \
        python3-pip  \
        python3-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir conan==1.45.0 cmake==3.21.0

WORKDIR /app

COPY conanfile.txt ./


RUN conan remote add cyberduckninja http://conan.cyberduckninja.com:9300  && \
    conan install -if build . --build missing -s build_type=Release -s compiler.libcxx=libstdc++11&& \
    ls && \
    pwd

COPY . ./

WORKDIR ./build

RUN cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON && \
    cmake --build .  --target duck_charmer

CMD ctest -V
