FROM k0tb9g9m0t/manylinux-bazel-2014 as build_wheel

RUN yum install -y ninja-build python3-pip wget unzip zip gcc-c++ java-11-openjdk-devel

RUN  pip3 install --no-cache-dir conan==1.59.0 pytest==6.2.5
RUN  conan user
RUN  conan profile new default --detect --force
RUN  conan profile update settings.compiler.libcxx=libstdc++11 default
RUN  conan config set general.parallel_download=$(nproc)
RUN  conan config set general.cpu_count=$(nproc)
RUN  conan remote add duckstax http://conan.duckstax.com

WORKDIR /app

COPY ./conanfile.txt ./conanfile.txt
RUN conan install . --build missing  \
    --build fmt \
    --build spdlog  \
    --build rocksdb  \
    -s build_type=Release

COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./wasm ./wasm
COPY ./CMakeLists.txt ./CMakeLists.txt

RUN cp integration/python/ottergon/* .
#RUN cp integration/python/ottergon/MANIFEST.in .
#RUN cp integration/python/ottergon/pyproject.toml .
#RUN cp integration/python/ottergon/get_path.py .
RUN mkdir -p /app/wasm_bin/
COPY --from=build_wasm /app/build/bin/*.wasm /app/wasm_bin/
RUN ls
RUN ls wasm_bin
#./components/wasm_runner/tests/

RUN   PYBIN=(/opt/python/*/bin) && \
      for BIN in "${PYBIN[@]}";  do  \
      if [[  ${BIN} == *"cp311"* ]]; then \
          ${BIN}/python3 -m pip install --no-cache-dir  wheel setuptools scikit-build==0.16.4  && \
          mkdir -p $(echo "./$(${BIN}/python3 get_path.py )") && \
          conan install . -s build_type=Release -if=$(echo "./$(${BIN}/python3 get_path.py )") && \
          ${BIN}/python3 setup.py bdist_wheel  --verbose  -DDEV_MODE=ON && \
          #${BIN}/python3 -m pip install --no-index --find-links . dist/ottergon-*.whl  && \
          cp /app/wasm_bin/*.wasm $(echo "./$(${BIN}/python3 get_path.py )/components/wasm_runner/tests/") && \
          cd $(echo "./$(${BIN}/python3 get_path.py )") && \
          ctest  -C --output-on-failure && \
          #pytest && \
          cd /app ; \
      fi \
      done

WORKDIR /app
RUN for whl in dist/ottergon*.whl; do \
        auditwheel repair ${whl} -w ./work/dist/  &&\
        rm ${whl}; \
    done

FROM ubuntu:20.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3-pip \
        python3-venv && \
    pip3 install --no-cache-dir pytest==6.2.5

WORKDIR /app

COPY --from=build_wheel /app/work/dist/ottergon-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /app/ottergon-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
COPY ./integration  ./integration

RUN pip3 install ./ottergon-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
RUN python3 -c "from ottergon import Client, DataBase, Collection"
RUN pytest