FROM ubuntu:20.04 as build_wasm

ENV TZ=America/US
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        ninja-build \
        python3-pip \
        python3-venv \
        python3-dev curl gnupg apt-transport-https && \
    curl -fsSL https://bazel.build/bazel-release.pub.gpg | apt-key add && \
        echo 'deb https://storage.googleapis.com/bazel-apt stable jdk1.8' | tee /etc/apt/sources.list.d/bazel.list && \
        apt update && \
        apt install -y bazel bazel-4.1.0 git && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN    pip3 install --no-cache-dir conan==1.52.0 cmake && \
    conan user && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan remote add duckstax http://conan.duckstax.com

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

WORKDIR /app/build
COPY conan/profiles/wasm ./conan/profiles/wasm
RUN conan config install conan
RUN ls -las
COPY conanfile-client-wasm.txt ./conanfile-client-wasm.txt
RUN conan install -pr wasm --profile:build=default --profile:host=wasm -g=virtualenv --build missing -s build_type=Release conanfile-client-wasm.txt

WORKDIR /app
COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./wasm ./wasm
COPY ./CMakeLists.txt ./CMakeLists.txt

WORKDIR /app/build
RUN source ./activate.sh  && \
    cmake  ..  -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN/cmake/Modules/Platform/Emscripten.cmake -DDEV_MODE=OFF -DWASM_BUILD=ON &&\
    cmake --build .

FROM k0tb9g9m0t/manylinux-bazel-2014 as build_wheel

RUN yum install -y ninja-build python3-pip wget unzip zip gcc-c++ java-11-openjdk-devel

RUN  pip3 install --no-cache-dir conan==1.52.0 pytest==6.2.5
RUN  conan user
RUN  conan profile new default --detect --force
RUN  conan profile update settings.compiler.libcxx=libstdc++11 default
RUN  conan config set general.parallel_download=$(nproc)
RUN  conan config set general.cpu_count=$(nproc)
RUN  conan remote add duckstax http://conan.duckstax.com

WORKDIR /app

COPY ./conanfile-host-wasm.txt ./conanfile-host-wasm.txt
RUN conan install conanfile-host-wasm.txt --build missing  \
    --build fmt \
    --build spdlog  \
    --build rocksdb  \
    -s build_type=Release

COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./wasm ./wasm
COPY ./CMakeLists.txt ./CMakeLists.txt

RUN cp integration/python/otterbrix/* .
#RUN cp integration/python/otterbrix/MANIFEST.in .
#RUN cp integration/python/otterbrix/pyproject.toml .
#RUN cp integration/python/otterbrix/get_path.py .
RUN mkdir -p /app/wasm_bin/
COPY --from=build_wasm /app/build/bin/*.wasm /app/wasm_bin/
RUN ls
RUN ls wasm_bin
#./components/wasm_runner/tests/

RUN   PYBIN=(/opt/python/*/bin) && \
      for BIN in "${PYBIN[@]}";  do  \
      if [[  ${BIN} == *"cp38"* ]]; then \
          ${BIN}/python3 -m pip install --no-cache-dir  wheel setuptools scikit-build && \
          mkdir -p $(echo "./$(${BIN}/python3 get_path.py )") && \
          conan install . -s build_type=Release -if=$(echo "./$(${BIN}/python3 get_path.py )") && \
          ${BIN}/python3 setup.py bdist_wheel  --verbose  -DDEV_MODE=ON && \
          #${BIN}/python3 -m pip install --no-index --find-links . dist/otterbrix-*.whl  && \
          cp /app/wasm_bin/*.wasm $(echo "./$(${BIN}/python3 get_path.py )/components/wasm_runner/tests/") && \
          cd $(echo "./$(${BIN}/python3 get_path.py )") && \
          ctest  -C --output-on-failure && \
          #pytest && \
          cd /app ; \
      fi \
      done

WORKDIR /app
RUN for whl in dist/otterbrix*.whl; do \
        auditwheel repair ${whl} -w ./work/dist/  &&\
        rm ${whl}; \
    done

FROM ubuntu:20.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3-pip \
        python3-venv && \
    pip3 install --no-cache-dir pytest==6.2.5

WORKDIR /app

COPY --from=build_wheel /app/work/dist/otterbrix-1.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /app/otterbrix-1.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
COPY ./integration  ./integration

RUN pip3 install ./otterbrix-1.0.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
RUN python3 -c "from otterbrix import Client, DataBase, Collection"
RUN pytest