FROM quay.io/pypa/manylinux2014_x86_64

#ENV TZ=America/US
#ENV DEBIAN_FRONTEND=noninteractive

RUN yum install -y  \
    ninja-build  \
    wget  \
    unzip  \
    java-11-openjdk-devel  \
    git  \
    gflags-devel  \
    snappy-devel  \
    zlib-devel  \
    bzip2-devel  \
    gcc-c++  \
    libstdc++-devel

RUN git clone https://github.com/facebook/rocksdb.git

WORKDIR /rocksdb
RUN ls

RUN mkdir build
WORKDIR /rocksdb/build
RUN cmake .. -DWITH_GFLAGS=OFF
RUN make -j 5
#RUN yum install -y cmake