FROM quay.io/pypa/manylinux2014_x86_64 as build_wheel

ENV PYTHONFAULTHANDLER=1

RUN yum install -y ninja-build python3-pip python3-devel wget unzip zip devtoolset-10-binutils devtoolset-10-gcc devtoolset-10-gcc-c++

RUN  pip3 install --no-cache-dir conan==1.64.0 pytest==6.2.5
RUN  conan user
RUN  conan profile new default --detect --force
RUN  conan profile update settings.compiler.libcxx=libstdc++11 default
RUN  conan config set general.parallel_download=$(nproc)
RUN  conan config set general.cpu_count=$(nproc)
RUN  conan remote add duckstax http://conan.duckstax.com

WORKDIR /app

COPY ./conanfile.txt ./conanfile.txt
RUN conan install . --build missing  \
    --build fmt \
    --build spdlog  \
    -s build_type=Release

COPY ./integration ./integration
COPY ./cmake ./cmake
COPY ./components ./components
COPY ./core ./core
COPY ./services ./services
COPY ./example ./example
COPY ./CMakeLists.txt ./CMakeLists.txt

RUN cp integration/python/otterbrix/* .
#RUN cp integration/python/otterbrix/MANIFEST.in .
#RUN cp integration/python/otterbrix/pyproject.toml .
#RUN cp integration/python/otterbrix/get_path.py .

RUN   PYBIN=(/opt/python/*/bin) && \
      for BIN in "${PYBIN[@]}";  do  \
      if [[  ${BIN} == *"cp311"* ]]; then \
          ${BIN}/python3 -m pip install --no-cache-dir  wheel setuptools scikit-build==0.16.4  && \
          mkdir -p $(echo "./$(${BIN}/python3 get_path.py )") && \
          conan install . -s build_type=Release -g CMakeDeps -if=$(echo "./$(${BIN}/python3 get_path.py )") && \
          ${BIN}/python3 setup.py bdist_wheel  --verbose -DDEV_MODE=ON && \
          #${BIN}/python3 -m pip install --no-index --find-links . dist/otterbrix-*.whl  && \
          cd $(echo "./$(${BIN}/python3 get_path.py )") && \
          ctest  -C -V --output-on-failure --timeout 60 && \
          #pytest -v && \
          cd /app ; \
      fi \
      done

WORKDIR /app
RUN for whl in dist/otterbrix*.whl; do \
        auditwheel repair ${whl} -w ./work/dist/  &&\
        rm ${whl}; \
    done

FROM ubuntu:20.04

RUN apt update && \
    apt upgrade -y && \
    apt install -y \
        python3-pip \
        python3-venv && \
    pip3 install --no-cache-dir pytest==6.2.5

WORKDIR /app

COPY --from=build_wheel /app/work/dist/otterbrix-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl /app/otterbrix-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
COPY ./integration  ./integration

RUN pip3 install ./otterbrix-0.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
RUN python3 -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))"
RUN python3 -c "from otterbrix import Client, DataBase, Collection, Connection, Cursor"
RUN catchsegv pytest -v -s