FROM ubuntu:20.04

RUN ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    apt update && \
    apt upgrade -y && \
    apt install -y \
        build-essential \
        cmake \
        ninja-build \
        python3-pip \
        python3-dev && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --no-cache-dir conan==1.48.0 pytest==6.2.5 && \
    conan user && \
    conan profile new default --detect --force && \
    conan profile update settings.compiler.libcxx=libstdc++11 default && \
    conan profile new emscripten-module && \
    conan profile update settings.compiler=clang emscripten-module && \
    conan profile update settings.compiler.version=15 emscripten-module && \
    conan profile update settings.compiler.libcxx=libc++ emscripten-module && \
    conan profile update settings.arch=wasm emscripten-module && \
    conan profile update settings.os=Emscripten emscripten-module && \
    echo -e 'LDFLAGS=--no-entry -s STANDALONE_WASM -s PURE_WASI=1 -s ABORTING_MALLOC=0 -s EXPORTED_FUNCTIONS=['_malloc'] -s ERROR_ON_UNDEFINED_SYMBOLS=0\n[tool_requires]\nemsdk/3.1.7' >> "${HOME}/.conan/profiles/emscripten-module" && \
    conan config set general.parallel_download=$(nproc) && \
    conan config set general.cpu_count=$(nproc) && \
    conan remote add duckstax http://conan.duckstax.com:9300 && \
    conan remote list

WORKDIR /app/build

COPY conanfile.txt ./

RUN conan install . --build missing -s build_type=Release

COPY . ../

WORKDIR /app/build

RUN cmake .. -DCMAKE_BUILD_TYPE=Release -DDEV_MODE=ON &&\
    cmake --build . --parallel

CMD ctest -V &&\
    pytest
