FROM quay.io/pypa/manylinux2014_x86_64

RUN yum install -y ninja-build python3-pip wget unzip zip gcc-c++ java-11-openjdk-devel
RUN wget https://releases.bazel.build/4.1.0/release/bazel-4.1.0-dist.zip
RUN unzip bazel-4.1.0-dist.zip -d bazel
RUN ls -l /usr/lib/jvm/
RUN        PYTHON_PATH=/opt/python/cp39-cp39 &&\
        JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.15.0.9-2.el7_9.x86_64" &&\

        PATH=$PYTHON_PATH:$PATH:$JAVA_HOME/bin &&\
        ln -sf /usr/local/bin/python3.9 /usr/bin/python &&\

        cd bazel &&\
        pwd && \
        ls &&\
        ./compile.sh  && \
        pwd && \
        ls output && \
        cp  ./output/bazel /usr/bin && \
        bazel --version