FROM python:3.8-slim as compile-image

RUN apt-get update && apt-get install -y --no-install-recommends gcc build-essential libpq-dev git

COPY ./tests/requirements.txt /
COPY ./tests/app/tasks.py /
COPY ./tests/client.py /
WORKDIR /venv
RUN python -m venv .
RUN /venv/bin/pip install --upgrade pip && /venv/bin/pip install --no-cache-dir -r /requirements.txt

WORKDIR /
CMD ["python3.8", "client.py"]
